const data = [
  {
    key: 1,
    content: "心是慈悲度己度人度含識\n\n法成清浄了塵了意了妄緣",
    year: "1903（光绪二十九年）",
    location: "大雄宝殿",
    poet: "陈门苏氏",
    remarks: "",
  },
  {
    key: 2,
    content: "福地振禪宗喜萬卷金經初譒竺國\n\n蓮山開法界與千年覺樹共蔭新州",
    year: "1903（光绪二十九年）",
    location: "大雄宝殿",
    poet: "刘门陈氏",
    remarks: "",
  },
  {
    key: 3,
    content:
      "光奪恒星先孔耶回以千秋東亞為 四洲聖\n\n宗傳象教合佛法僧之三寶西竺成一家言",
    year: "1904（光绪三十年）",
    location: "大雄宝殿",
    poet: "邱炜萲（邱菽园）",
    remarks: "",
  },
  {
    key: 4,
    content: "定慧雙輪舌吐蓮花開大觉\n\n慈悲一片指彈甘露潤群黎",
    year: "1904（光绪三十年）",
    location: "大雄宝殿",
    poet: "息理末等",
    remarks: "",
  },

  {
    key: 5,
    content:
      "福地俯大千梵宇鼎新寶相莊嚴輪慧日\n\n蓮山開第一禪宗宏衍曇蘤馥鬱蔭慈雲",
    year: "1904（光绪三十年）",
    location: "大雄宝殿",
    poet: "颜仕份",
    remarks: "",
  },

  {
    key: 6,
    content: "塵埃半點不到地\n\n花木四時長是春",
    year: "1904（光绪三十年）",
    location: "大雄宝殿",
    poet: "刘金榜",
    remarks: "",
  },

  {
    key: 7,
    content: "樹法雨以長靈苗故稱化主\n\n引迷途而登覺岸是謂導師",
    year: "1904（光绪三十年）",
    location: "大雄宝殿",
    poet: "王君子",
    remarks: "",
  },
  {
    key: 8,
    content: "人相即非一片湖光參色界\n\n我佛如是四圍松籟悟禪機",
    year: "1904（光绪三十年）",
    location: "大雄宝殿",
    poet: "邱德松",
    remarks: "见于福州西禅寺，文字稍不同",
  },

  {
    key: 9,
    content: "引領瞻天羨金相玉毫居法界\n\n瓣香祝聖愿慈雲甘露被人寰",
    year: "1904（光绪三十年）",
    location: "大雄宝殿",
    poet: "杨本陞",
    remarks: "",
  },

  {
    key: 10,
    content: "	苦況祇自知六載寒岩嘗傲雪\n\n化機忻普被五洲精舍漸生雲",
    year: "1904（光绪三十年）",
    location: "大雄宝殿",
    poet: "林門李氏世娘",
    remarks: "",
  },

  {
    key: 11,
    content: "破夢幻影泡曾向昏衢燃法炬\n\n度生老病死常於苦海篤慈航",
    year: "1904（光绪三十年）",
    location: "大雄宝殿",
    poet: "刘金榜",
    remarks: "",
  },
  {
    key: 12,
    content: "最上教乘羅列七覺八正\n\n無邊法力俱是五眼六通",
    year: "1904（光绪三十年）",
    location: "大雄宝殿",
    poet: "张门□□",
    remarks: "",
  },
  {
    key: 13,
    content: "功德林中一一蒲團依樾蔭\n\n蓮花座下聲聲貝葉頌檀勛",
    year: "1904（光绪三十年）",
    location: "法堂",
    poet: "住持明光",
    remarks: "",
  },
  {
    key: 14,
    content: "鹿苑布金遙憶當年長者\n\n雞園飾玉欣瞻此日祇林",
    year: "1904（光绪三十年）",
    location: "法堂",
    poet: "陈宝琛",
    remarks: "",
  },

  {
    key: 15,
    content: "無事渡溪橋洗鉢歸來雲滿袖\n\n有緣修佛界談經空處雨飛花",
    year: "1905（光绪三十一年）",
    location: "天王殿",
    poet: "佚名",
    remarks: "见于浙江永嘉隆平寺等处",
  },
  {
    key: 16,
    content: "一水縈回樹色蒼茫蘭若靜\n\n萬山環繞鐘聲迢遞白雲深",
    year: "1905（光绪三十一年）",
    location: "天王殿",
    poet: "鄭熾",
    remarks: "",
  },
  {
    key: 17,
    content: "萬境幽閒花影泉聲俱寂\n\n山林清靜禪心法味同彌",
    year: "1905（光绪三十一年）",
    location: "弥勒殿",
    poet: "薛门谢妳媚",
    remarks: "",
  },

  {
    key: 18,
    content: "叻嶼泊慈航一乘原為最上乘\n\n蓮山開法苑雙林即是大叢林",
    year: "1905（光绪三十一年）",
    location: "弥勒殿",
    poet: "刘金榜",
    remarks: "",
  },

  {
    key: 19,
    content: "星嶼縱橫蓮開金葉\n\n萬山功德剎建雙林",
    year: "1905（光绪三十一年）",
    location: "天王殿",
    poet: "刘丕显",
    remarks: "",
  },

  {
    key: 20,
    content: "創建肇萬山金精耿耿神祇護\n\n莊嚴昭千載玉宇巍巍龍象朝",
    year: "1905（光绪三十一年）",
    location: "天王殿",
    poet: "刘门陈氏",
    remarks: "",
  },

  {
    key: 21,
    content: "五眼圓明金易化\n\n三心未了水難消",
    year: "1905（光绪三十一年）",
    location: "斋堂",
    poet: "主持明光",
    remarks: "改自《五灯会元》",
  },
  {
    key: 22,
    content: "鐵脊樑將勤補拙\n\n金剛屑易食難消",
    year: "1905（光绪三十一年）",
    location: "斋堂",
    poet: "刘金榜",
    remarks: "见于福州涌泉寺斋堂",
  },

  {
    key: 23,
    content: "妙宣奧偈天花落\n\n端坐禪房春草深",
    year: "1905（光绪三十一年）",
    location: "天王殿",
    poet: "林月官",
    remarks: "",
  },

  {
    key: 24,
    content: "山色水光齊呈妙相\n\n花香鳥語共露玄機",
    year: "1905（光绪三十一年）",
    location: "天王殿",
    poet: "林門李氏世良",
    remarks: "",
  },
  {
    key: 25,
    content: "景教亙重瀛西土宗風終不墜\n\n市場通九譯南溟精舍此無塵",
    year: "1906（光绪三十二年）",
    location: "天王殿",
    poet: "刘广墻启东启祥",
    remarks: "",
  },
  {
    key: 26,
    content: "世外無非歡喜地\n\n空中即是故人鄉",
    year: "1907（光绪三十三年）",
    location: "斋堂",
    poet: "刘启东",
    remarks: "",
  },
  {
    key: 27,
    content: "此地踞萬山最頂\n\n當年說諸石點頭",
    year: "1907（光绪三十三年）",
    location: "斋堂",
    poet: "刘广墻",
    remarks: "",
  },
  {
    key: 28,
    content: "寶筏渡迷津共仰禪心妙微﹝注 1﹞\n\n金繩開覺路咸瞻西土莊嚴",
    year: "1907（光绪三十三年）",
    location: "客堂",
    poet: "刘金榜",
    remarks: "",
  },
  {
    key: 29,
    content: "歡喜滿腔普利無邊國土\n\n慈悲一味弘開不二法門",
    year: "1907（光绪三十三年）",
    location: "客堂",
    poet: "住持敬輝",
    remarks: "",
  },
  {
    key: 30,
    content: "佛子生涯依禪靜\n\n法王宮殿隱煙霞",
    year: "1907（光绪三十三年）",
    location: "文物室",
    poet: "刘启祥",
    remarks: "",
  },
  {
    key: 31,
    content: "蓬梗萍飄共從身外證\n\n蘭因絮果好向佛前參",
    year: "1907（光绪三十三年）",
    location: "客堂",
    poet: "刘金榜",
    remarks: "",
  },
  {
    key: 32,
    content: "媧皇補天特留片石\n\n菩薩覺世藉闢雙林",
    year: "1907（光绪三十三年）",
    location: "大雄室殿",
    poet: "刘金榜",
    remarks: "",
  },
  {
    key: 33,
    content: "數聲柳巷蟬吟靜\n\n半榻松風鶴夢清",
    year: "1907（光绪三十三年）",
    location: "地藏殿",
    poet: "刘市娘",
    remarks: "",
  },
  {
    key: 34,
    content: "暮鼓晨鐘每以金繩開覺路\n\n慈雲法雨長將寶筏渡迷津",
    year: "1907（光绪三十三年）",
    location: "地藏殿",
    poet: "刘金榜",
    remarks: "",
  },
  {
    key: 35,
    content: "極清淨一塵不染\n\n無罣礙五蘊皆空",
    year: "1907（光绪三十三年）",
    location: "地藏殿",
    poet: "刘门白氏宝娘",
    remarks: "",
  },
  {
    key: 36,
    content: "萬法歸宗心埊長菩提之樹\n\n山靈護教帝天雨優鉢之花",
    year: "1907（光绪三十三年）",
    location: "地藏殿",
    poet: "刘锥娘",
    remarks: "",
  },
  {
    key: 37,
    content: "座上禪心都是慈雲法雨\n\n階前生意無非翠竹黃花",
    year: "1907（光绪三十三年）",
    location: "西配殿",
    poet: "邱美顺",
    remarks: "",
  },
  {
    key: 38,
    content: "福地鼓鐘花雨匝\n\n僊山樓閣碧雲深",
    year: "1907（光绪三十三年）",
    location: "伽蓝殿",
    poet: "刘长寿",
    remarks: "",
  },
  {
    key: 39,
    content: "廿五圓通度世以無量\n\n十八羅漢奉佛為至尊",
    year: "1907（光绪三十三年）",
    location: "伽蓝殿",
    poet: "刘金榜",
    remarks: "",
  },

  {
    key: 40,
    content: "貝葉曇花來白馬\n\n慈雲法雨護青蓮",
    year: "1907（光绪三十三年）",
    location: "伽蓝殿",
    poet: "刘大耳",
    remarks: "",
  },
  {
    key: 41,
    content:
      "鼇海舊因緣山翠湖光福地林泉開勝景\n\n龍天新氣象心燈意蕊梵莒花月亦禪機",
    year: "1907（光绪三十三年）",
    location: "伽蓝殿",
    poet: "陈木生",
    remarks: "",
  },

  {
    key: 42,
    content: "萬德圓融破有法王福慧兩足\n\n山林寂靜出塵世界風月雙清",
    year: "1907（光绪三十三年）",
    location: "鼓楼",
    poet: "刘金榜",
    remarks: "",
  },

  {
    key: 43,
    content: "岸邊竹影連窗秀\n\n池上荷花入座香",
    year: "1907（光绪三十三年）",
    location: "文物室",
    poet: "刘启东",
    remarks: "",
  },
  {
    key: 44,
    content: "塵心棲息無餘事\n\n禪室幽閒獨自由",
    year: "1907（光绪三十三年）",
    location: "文物室",
    poet: "刘广墻",
    remarks: "",
  },
  {
    key: 45,
    content: "身如枯木寒巖三冬發暖\n\n心似澄江皓魄萬里長明",
    year: "1907（光绪三十三年）",
    location: "文物室",
    poet: "刘金榜",
    remarks: "",
  },
  {
    key: 46,
    content: "飛錫徐來常返鶴\n\n度杯遠至不驚鷗",
    year: "1907（光绪三十三年）",
    location: "文物室",
    poet: "刘初香",
    remarks: "",
  },
  {
    key: 47,
    content: "色相皆空六根清淨方成佛\n\n法輪常轉一塵不染乃為僧",
    year: "1907（光绪三十三年）",
    location: "祖堂",
    poet: "刘金榜",
    remarks: "",
  },

  {
    key: 48,
    content: "明鏡無臺法輪可照暗室\n\n菩提有樹寶筏能渡迷津",
    year: "1907（光绪三十三年）",
    location: "斋堂",
    poet: "刘金榜",
    remarks: "",
  },

  {
    key: 49,
    content: "功在山林名垂宇宙\n\n德興一念祀享千秋",
    year: "1907（光绪三十三年）",
    location: "功德堂",
    poet: "刘锥娘",
    remarks: "",
  },
  {
    key: 50,
    content: "攬五洲最勝地鎮此金山\n\n覺一切有情人現來鐵漢",
    year: "1907（光绪三十三年）",
    location: "功德堂",
    poet: "刘金榜",
    remarks: "",
  },

  {
    key: 51,
    content: "佛法無邊皈依何止四眾\n\n善門廣大修證共尊雙林",
    year: "1907（光绪三十三年）",
    location: "钟楼",
    poet: "刘金榜",
    remarks: "",
  },
  {
    key: 52,
    content: "性地虛靈明光夜見峰頭月\n\n心淵清淨妙道時開火裡蓮",
    year: "1907",
    location: "大雄宝殿",
    poet: "佚名",
    remarks: "见于西禅寺大雄宝殿",
  },
  {
    key: 53,
    content: "大家若得閒閒來方外地\n\n老僧本好靜靜悟道中機",
    year: "1907",
    location: "祖堂",
    poet: "佚名",
    remarks: "",
  },

  {
    key: 54,
    content: "曇華獻瑞禪林靜\n\n萎草分芳法界深",
    year: "1907",
    location: "祖堂",
    poet: "佚名",
    remarks: "",
  },

  {
    key: 55,
    content: "北秀南能女后且為護法主\n\n三皈五戒嶽神亦是聽參人",
    year: "1907",
    location: "东配殿",
    poet: "佚名",
    remarks: "",
  },
  {
    key: 56,
    content: "依即心自性現身而說法\n\n顯隨類逐形救苦以尋聲",
    year: "1993",
    location: "观音殿",
    poet: "松年法师",
    remarks: "",
  },
  {
    key: 57,
    content:
      "儒佛水乳交融應有慧遠淵明一輩人物嘯咏生緣好為蓮山結蓮社\n\n東西海空樞紐但願椰風蕉雨多元種族和平共處永瞻星島耀星旗",
    year: "1996",
    location: "大雄宝殿",
    poet: "住持谈禅立/潘受撰书",
    remarks: "",
  },
  {
    key: 58,
    content: "雙清茂繞蓮座\n\n林翠花承神機",
    year: "1996",
    location: "西配殿",
    poet: "松年法师",
    remarks: "",
  },

  {
    key: 59,
    content: "盈月景光悲舊\n\n素心興會殊前",
    year: "1996",
    location: "东配殿",
    poet: "松年法师",
    remarks: "",
  },

  {
    key: 60,
    content: "香雲普覆真如界\n\n皓月常明自在天",
    year: "1996",
    location: "天王殿",
    poet: "松年法师",
    remarks: "乾隆题北京智珠寺",
  },

  {
    key: 61,
    content: "此處有僧皆佛印\n\n往來無客不東坡",
    year: "1996",
    location: "西配殿",
    poet: "松年法师",
    remarks: "此现成句",
  },

  {
    key: 62,
    content: "信知大事因緣暢說法華明一乘\n\n證得無量壽命永垂足跡現雙林",
    year: "1996",
    location: "大雄宝殿",
    poet: "赵朴初",
    remarks: "",
  },

  {
    key: 63,
    content: "寂歸日月周旋外\n\n活在親朋記憶中",
    year: "1997",
    location: "功德堂",
    poet: "潘受",
    remarks: "",
  },

  {
    key: 64,
    content: "祖印重光寒立雪\n\n宗風永振夜傳衣",
    year: "1999",
    location: "祖堂",
    poet: "超尘法师撰/许梦丰书",
    remarks: "",
  },
  {
    key: 65,
    content: "雙修福慧三摩地\n\n林接雲霞萬里天",
    year: "1999",
    location: "牌楼",
    poet: "腾光法师撰/王之鏻书",
    remarks: "",
  },
  {
    key: 66,
    content: "不二法門諸佛行處\n\n大千世界群生道場",
    year: "1999",
    location: "牌楼",
    poet: "腾光法师撰/王之鏻书",
    remarks: "",
  },

  {
    key: 67,
    content: "大道恢宏傳妙諦\n\n名山高峻仰宗風",
    year: "1999",
    location: "牌楼",
    poet: "腾光法师撰/王之鏻书",
    remarks: "",
  },

  {
    key: 68,
    content: "殿宇巍峨莊嚴三寶\n\n煙霞靄瑞毓秀雙林",
    year: "1999",
    location: "牌楼",
    poet: "腾光法师撰/王之鏻书",
    remarks: "",
  },

  {
    key: 69,
    content: "光明心地菩提地\n\n磊落山門般若門",
    year: "1999",
    location: "牌楼",
    poet: "腾光法师撰/王之鏻书",
    remarks: "",
  },

  {
    key: 70,
    content: "八水雙林澤敷閩海\n\n一花五葉法被星洲",
    year: "1999",
    location: "牌楼",
    poet: "腾光法师撰/王之鏻书",
    remarks: "",
  },

  {
    key: 71,
    content: "雙樓月明昭覺路\n\n林泉水淨出迷津",
    year: "1999",
    location: "牌楼",
    poet: "腾光法师撰/王之鏻书",
    remarks: "",
  },
  {
    key: 72,
    content: "北地慈門功跨孺素\n\n南天名剎化及華夷",
    year: "1999",
    location: "牌楼",
    poet: "腾光法师撰/王之鏻书",
    remarks: "",
  },
  {
    key: 73,
    content: "歸宗一念真常淨\n\n樓閣頓開彌勒門",
    year: "2000",
    location: "般若室",
    poet: "佛源法师",
    remarks: "",
  },
  {
    key: 74,
    content: "謢法安僧親受靈山咐囑\n\n降魔伏怨故現天將威風",
    year: "2000",
    location: "天王殿",
    poet: "赖瑞龙篆",
    remarks: "",
  },
  {
    key: 75,
    content: "思親致孝千家祀\n\n報本崇源萬世尊",
    year: "2001",
    location: "报本堂",
    poet: "纪策",
    remarks: "",
  },

  {
    key: 76,
    content: "萬類歸根成佛性\n\n千秋祭祀念親恩",
    year: "2001",
    location: "报本堂",
    poet: "纪策",
    remarks: "",
  },

  {
    key: 77,
    content: "梵音上徹三千界\n\n法藏綜含八萬門",
    year: "2001",
    location: "山门",
    poet: "水国章赠/许梦丰撰书",
    remarks: "",
  },

  {
    key: 78,
    content: "寶殿巍峨規製遙承八閩\n\n因緣具足眾生普樂三施",
    year: "2001",
    location: "山门",
    poet: "钟声坚赠/许梦丰撰书",
    remarks: "",
  },
  {
    key: 79,
    content: "碧松影裏天常靜\\n\n红藕花開水亦香",
    year: "2001",
    location: "钟楼",
    poet: "一音法师书",
    remarks: "见于陕西略阳书院",
  },

  {
    key: 80,
    content: "恆以大音宣正法\n\n當念本願度眾生",
    year: "2001",
    location: "天王殿",
    poet: "一音法师书",
    remarks: "集《华严经》句",
  },

  {
    key: 81,
    content: "清韻不隨夜月轉\n\n餘音常傍暮雲流",
    year: "2001",
    location: "鼓楼",
    poet: "佚名",
    remarks: "",
  },

  {
    key: 82,
    content: "見佛自在心歡喜\n\n發心迴向趣菩提",
    year: "2001",
    location: "天王殿",
    poet: "一音法师书",
    remarks: "集《华严经》句",
  },

  {
    key: 83,
    content: "出生無上菩提樹\n\n長養最勝智慧門",
    year: "2001",
    location: "般若室",
    poet: "弘一法师",
    remarks: "集《华严经》句",
  },
  {
    key: 84,
    content: "佛意教意西來意\n\n身如口如心也如",
    year: "2003",
    location: "禅堂",
    poet: "佛源法师",
    remarks: "",
  },

  {
    key: 85,
    content:
      "龍王護法和風好雨隨時令浮圖七級高鎮梵宇\n\n光華普輝十界諸天共歡欣瑞靄八方蔭庇獅城",
    year: "2003",
    location: "斋堂",
    poet: "许梦丰",
    remarks: "此联为庆祝大雄宝殿天王殿重修圆竣暨龙光宝塔开幕而撰",
  },
  {
    key: 86,
    content: "有彌勒肚皮斗金易化\n\n無維摩手段滴水難消",
    year: "2007",
    location: "五观堂（斋堂）",
    poet: "佚名",
    remarks: "见于中国多处寺院的斋堂",
  },

  {
    key: 87,
    content: "是生計皆通妙喻\n\n能會心自不多言",
    year: "2010",
    location: "文物室",
    poet: "许梦丰撰书",
    remarks: "",
  },

  {
    key: 88,
    content: "圓音演妙法宏開梵宇\n\n滿願證菩提應現金容",
    year: "2016",
    location: "法堂圓滿殿",
    poet: "了中法师撰/许梦丰书",
    remarks: "",
  },

  {
    key: 89,
    content: "高提祖印直指曹溪祖意\n\n丕振禪綱遠承怡山禪風",
    year: "2016",
    location: "方丈室",
    poet: "了中法师撰/许梦丰书",
    remarks: "",
  },
  {
    key: 90,
    content: "問爾不答求之則應\n\n聽爾無聲叫則威靈",
    year: "不详",
    location: "双林城隍庙",
    poet: "佚名",
    remarks: "",
  },
  {
    key: 91,
    content: "爾欲欺心神未許\n\n君能瞞己我難瞞",
    year: "不详",
    location: "双林城隍庙",
    poet: "佚名",
    remarks: "此联见于其他庙宇",
  },
]

export default data
